
kafka:
  info:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
      auto-commit: false
  topics:
    transactions:
      polling-interval: 1000
      concurrency: 3
      max-poll-records: 500
      enabled: true
database:
  redis:
    host: localhost
    port: 6379
    database: 0
    password: ""
    timeout: 10000
  mongo:
    uri: ${MONGO_URI}
  redisson:
    host: redis://127.0.0.1:6379
    timeout: 10000
    password: ""
logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: INFO
    org.apache.kafka.clients.NetworkClient: ERROR
    org.apache.kafka.common.network.Selector: ERROR
    org.apache.kafka.clients.consumer: WARN
    org.apache.kafka.clients.Metadata: WARN
    org.example.cosumer.consumer.ConsumerFactory: INFO
spring:
  config:
    import: classpath:secret.properties